FROM golang:1.22.3 as builder

WORKDIR /go/src/app
COPY . .
RUN make build

FROM scratch
WORKDIR /
COPY --from=builder /go/src/app/kbot .
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENV TARGETOS=linux
ENV TARGETARCH=amd64

ENTRYPOINT ["./kbot", "start"]
